# 做集群时的配置
#spring:
#  data:
#    elasticsearch:
#      cluster-name: leyou-elastic
#      cluster-nodes: 127.0.0.1:9301,127.0.0.1:9302,127.0.0.1:9303

# 练习时的配置
spring:
  data:
    elasticsearch:
      cluster-name: my-application # 集群名称
      cluster-nodes: 127.0.0.1:9300 # 集群节点