server:
  port: 9001
spring:
  application:
    # 当前应用的服务名称(也叫服务id)
    name: hello-service-consumer
# 配置注册中心 eureka 的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka