server:
  port: 8080
spring:
  # 指定应用的名字
  application:
    name: user-service
  # 配置数据库连接四项
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_boot?characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: root
  # 配置返回时间的格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis-plus 自定义配置
mybatis-plus:
  global-config:
    db-config:
      # 数据库ID自增
      id-type: auto
      # 表名前缀
      table-prefix: t_
  configuration:
    # 打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启自动驼峰命名规则(camel case)映射,即从数据库字段名(列名) A_COLUMN (下划线命名) 到 Java 实体属性名 aColumn(驼峰命名) 的类似映射
    map-underscore-to-camel-case: true
